module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests'],
  testMatch: ['**/*.test.ts', '**/*.test.js', '**/*.spec.ts', '**/*.spec.js'],
  forceExit: true,
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['json', 'json-summary', 'text', 'lcov'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/main.ts',
    '!src/**/*.test.ts',
    '!src/auth/**',
    '!src/feed/**',
    '!src/categories/**',
    '!src/metadata/**',
    '!src/themes/**',
    '!src/common/audit.ts',
    '!src/common/utils.ts',
  ],
};